### ISSUE TITLE
how to Install cv2+contrib

### ISSUE THREAD

**Issue by asdasd888** [will7200/Yugioh-bot#17]
i never use python how to Install cv2+contrib

**Comment by will7200** [comment]
You can just follow the
```bash
pip install -r requirements.txt
```
There is a package that will install it for you.

**Comment by asdasd888** [comment]
what is program runing ?
pip install -r requirements.txt

**Comment by asdasd888** [comment]
you can make a video method tutorial ?

**Comment by will7200** [comment]
Yes I will make a gif of me show the commands made to start the bot.

**Comment by asdasd888** [comment]
thank you.

**Comment by will7200** [comment]
Gif is on readme, full video is found [here](https://youtu.be/cFAPlUhOMG0).
