### ISSUE TITLE
Hang before auto-duel button

### ISSUE THREAD

**Issue by thanoskat** [will7200/Yugioh-bot#21]
![untitled](https://user-images.githubusercontent.com/8171250/34662382-d310e910-f458-11e7-8f93-2261de0fdb97.png)

I am using the latest version

**Comment by will7200** [comment]
Create a folder named `tmp` in the root directory. The install.py script should have done that for you.

**Comment by thanoskat** [comment]
![untitled](https://user-images.githubusercontent.com/8171250/34680892-f3de8e14-f4a2-11e7-9f3a-9b6b1de5f4d8.png)

There is already one. Is this the path you ment?

**Comment by will7200** [comment]
Well according to the log, the tesseract command is not producing the output text from the input image. Where is tesseract installed?

**Comment by thanoskat** [comment]
![untitled](https://user-images.githubusercontent.com/8171250/34695588-1cc08e46-f4d4-11e7-9c8f-685ed9099d28.png)

C:\Program Files (x86)\Tesseract-OCR

**Comment by will7200** [comment]
Ok the install should have pointed to the bin folder in the root location. Otherwise people would have to add this on to their path to work correctly.

**Comment by thanoskat** [comment]
I dont get it. Should I add this to my path?

**Comment by thanoskat** [comment]
Can you elaborate?
Should I install tess in bin directory of bot?

**Comment by curtiola** [comment]
C:\Users\Thanos\Yugioh-bot\bin\tess

**Comment by thanoskat** [comment]
I think it is fixed now. But it clicks on wrong places like the Battle City Begins button or Duel School.
Should I open a separate issue?

**Comment by will7200** [comment]
It will click in wrong places since it uses an algorithm that approximates circles in the image, so there can be circles in pixel data but not visually.

**Comment by thanoskat** [comment]
I figured it out. Contents of tesseract should be in the bin/tess folder.
Just selecting bin/tess doesn't work in tesseract installation because it will create Tesseract-OCR folder first.

This is the correct path:

![untitled](https://user-images.githubusercontent.com/8171250/34721165-5cfba0a6-f54a-11e7-9753-bc5147d47e3d.png)
