### ISSUE TITLE
Python Version Help 

### ISSUE THREAD

**Issue by koreplay** [will7200/Yugioh-bot#25]
Quick question. I have multiple python versions and im trying to specify which on to use googled but can find answer. How do I make this command "python install.py" use python 3.5. I know with pip you do "pip3.5 install ex" how do i do this with "python install.py" thanks

**Comment by will7200** [comment]
Do you have conda installed or did you just install multiple versions of python from their download page?

**Comment by will7200** [comment]
Closing for no response. Look at conda is you want to have multiple python versions on one system without messing up your path variables.
