### ISSUE TITLE
[Bug] OpenCV error on loading black screen

### ISSUE THREAD

**Issue by koreplay** [will7200/Yugioh-bot#27]
I keep seeing this error OpenCV Error: Assertion failed (_queryDescriptors.type() == trainDescType) in cv::BFMatcher::knnMatchImpl, file C:\projects\opencv-python\opencv\modules\features2d\src\matchers.cpp, line 744? Also the bot tends to click sin blank spots very constant. Also tends to click the replay often.

**Comment by will7200** [comment]
The opencv error occurs when the whole screen is dark, I am not too sure exactly why though. I will look into it when time permits.

**Comment by will7200** [comment]
Fixed in 9eb97d1550c1a2f9b39f137878b5d217c3d305be
