### ISSUE TITLE
[Bug] Nox image capture Fails Occasionally 

### ISSUE THREAD

**Issue by koreplay** [will7200/Yugioh-bot#30]
2018-01-14 22:01 - DEBUG - bot - Timeout dump Scheduled
2018-01-14 22:01 - INFO - apscheduler.scheduler - Scheduler has been shut down

**Comment by will7200** [comment]
Can you give the whole log file?

**Comment by curtiola** [comment]
Not sure if it's the same since he didn't provide details, but I think it may have happened to me as well, just shut down randomly, here is some of the log: 
[random shutdown.txt](https://github.com/will7200/Yugioh-bot/files/1653232/random.shutdown.txt)

**Comment by will7200** [comment]
Looks like the image from Nox was not properly obtained and I don't handle that exception thus causing the scheduler to shut down but that should also shut down the program.

**Comment by curtiola** [comment]
It did indeed shut down the program
