### ISSUE TITLE
Bot occasionally doesn't Press Auto-Duel Correctly

### ISSUE THREAD

**Issue by will7200** [will7200/Yugioh-bot#4]
Implement a way to check that the auto-duel button was indeed clicked on

**Comment by koreplay** [comment]
Bot stuck at "2017-08-11 23:32:47,430 - bot - DEBUG - WAITING FOR AUTODUEL BUTTON TO APPEAR" 
ran over 50 times always get stuck there

**Comment by will7200** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #4: Bot occasionally doesn't Press Auto-Duel Correctly](https://trello.com/c/ic2lbhJ7/1-issue-4-bot-occasionally-doesnt-press-auto-duel-correctly)

**Comment by will7200** [comment]
resolved by commit 59830e052e1d371f3629f31bea98f70c38a15b83
