### ISSUE TITLE
It stops before entering a duel, tmp\\ocr.txt missing?

### ISSUE THREAD

**Issue by faber5594** [will7200/Yugioh-bot#40]
here the scan
![immagine](https://user-images.githubusercontent.com/35998149/35642312-0da6eb2a-06c3-11e8-9117-070d8434d6fe.jpg)

**Comment by will7200** [comment]
Did you run the install.py script. It will download tesseract for you and also tell you where to download the tesseract program, that or you don't' have a folder named tmp.

**Comment by faber5594** [comment]
Yes I downladed Tesseract and I have the folder tmp, is it maybe a problem of where I have the folder bot, should I update this string with my path User/bot/.../tmp?
![immagine](https://user-images.githubusercontent.com/35998149/35642947-07fbe0de-06c5-11e8-9cc7-3e08d95053fb.jpg)

**Comment by faber5594** [comment]
@will7200 wait should it be "tmp\ocr.txt" or "tmp\ocr.png"? cause in the tmp folder I just have a picture

**Comment by will7200** [comment]
@faber5594 there should be a ocr.png that needs to translate from image to txt. You are missing the tmp\ocr.txt. Look at #21 for reference as they had the same issue. Can you try running the command in the screenshot in the root directory('bin\tess\tesseract.exe ...') and give me the output?

**Comment by faber5594** [comment]
@will7200  should I run it from the shell right? If so this is the result bash: bintesstesseract.exe: command not found

**Comment by will7200** [comment]
@faber5594 tesseract wasn't installed properly you should be able to find the tesseract exe in the folder bin\tess\ directory

**Comment by will7200** [comment]
Resolved in #41 per @faber5594
