### ISSUE TITLE
Any update for all players that dont have the high resolution of 1606x929 ???

### ISSUE THREAD

**Issue by salvatore1994** [will7200/Yugioh-bot#43]
Hi guys i was waiting since 2 month for any update for this proble, is there any news ?

**Comment by will7200** [comment]
@salvatore1994 I am working on it, it is currently not 100% consistent. I may just have to predefine another resolution settings.

**Comment by salvatore1994** [comment]
@will7200  would be great if you could add a resolution for 1152x648 💃  or even 1280x720 :)

**Comment by will7200** [comment]
@salvatore1994 closing for now. Monitor #34 for any updates.
