### ISSUE TITLE
IS THE .EXE release legit or did you get hacked lol got spammed just making sure?

### ISSUE THREAD

**Issue by koreplay** [will7200/Yugioh-bot#52]
??? You excited?

**Comment by will7200** [comment]
LOL this is terrible

**Comment by will7200** [comment]
Yeah its legit APPVEYOR was giving me issues with upload sizes after 1000 mb so I was trying relentlessly to get it working.

**Comment by will7200** [comment]
Jk this was due to appveyor rebuilding the same commit over and over again

**Comment by will7200** [comment]
I fixed them all
