### ISSUE TITLE
Having problems installing

### ISSUE THREAD

**Issue by MMestre23** [will7200/Yugioh-bot#63]
I get this error when running the 'python install.py' command

Component 3: Checking required packages
Traceback (most recent call last):
  File "install.py", line 208, in <module>
    main_install()
  File "install.py", line 204, in main_install
    command_runner(command[1])
  File "install.py", line 191, in command_runner
    comm()
  File "install.py", line 150, in check_required_packages
    installed_packages = pip.get_installed_distributions()
AttributeError: module 'pip' has no attribute 'get_installed_distributions'

I'm using the steam version.
Any idea how to fix it?

**Comment by will7200** [comment]
What version of pip are you running?

**Comment by will7200** [comment]
I believe there was breaking changes in their api for 10 so I will look at it when I get the chance.

**Comment by MMestre23** [comment]
Thanks

**Comment by MMestre23** [comment]
Any updates on the situation?

**Comment by will7200** [comment]
@MMestre23 I fixed this in 66168fb80437e84ba41fec0cbe2499db0d6a4e48 thank you for your patience.
