### ISSUE TITLE
No Nox folder in roaming.

### ISSUE THREAD

**Issue by SpiritEnvy** [will7200/Yugioh-bot#67]
Just as the title says i have no nox folder in roaming i tried manually i tried automatically is still doesnt work. Tried restarting nox nothing at all.

**Comment by will7200** [comment]
@SpiritEnvy this is to copy the adb executable and the required dll right?

**Comment by SpiritEnvy** [comment]
Yes sir, i cant copy it to there and if i run the install it cant install there so I'm not to sure what to do.

**Comment by will7200** [comment]
Where is Nox installed? You can get a clue from right-clicking the shortcut icon on the desktop or windows bar file location.

**Comment by SpiritEnvy** [comment]
Sorry for being a pain but thanks for working with me ill just move on. Your a great person for trying to help though sir. :D
