### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by koreplay** [will7200/Yugioh-bot#9]
So I followed the steps now I get this "ImportError: No module named 'win32gui'" and when I pip install the wheel file I get this is already satisfied thougths?

**Comment by AIRuni** [comment]
You must install python's module "win32gui".
Download from https://sourceforge.net/projects/pywin32/files/pywin32/
and install.

**Comment by will7200** [comment]
If you are using the correct python environment, python 3.5, pip should install win32gui when you do the following command 
``` bash
$ pip install -r requirements.txt 
```
If you are using conda, here is a powershell script that will help
``` powershell
$ Get-Content requirements.txt | ForEach-Object {
conda install --yes $_
}
```
